image: "python:2.7"

stages:
  - test
  - style

style:
  stage: style
  script:
  - pip install pylint
  - find . -iname "*.py" | xargs pylint
  tags: [kuber-internet-shared]

test:
  stage: test
  script:
  - pip install -r requirements.txt
  tags: [kuber-internet-shared]